using System.Collections.Generic;

namespace AutoTranslator_Core.Workflow
{
    internal static class BuiltInReferenceDictionary
    {
        // Curated from local official English Def labels and ChineseSimplified language archives.
        internal static IEnumerable<ReferenceDictionaryEntry> Entries()
        {
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:GoJuice.label", TargetLanguage = "ChineseSimplified", SourceForm = "go-juice", TargetForm = "活力水", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld 药物名称，战斗兴奋剂；不是普通果汁。", SourceReference = "Core/Defs/Drugs/GoJuice.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/GoJuice.xml#GoJuice.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Luciferium.label", TargetLanguage = "ChineseSimplified", SourceForm = "luciferium", TargetForm = "魔鬼素", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld 的魔鬼素药物名称，使用该游戏物品的义项。", SourceReference = "Core/Defs/Drugs/Luciferium.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Luciferium.xml#Luciferium.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Neutroamine.label", TargetLanguage = "ChineseSimplified", SourceForm = "neutroamine", TargetForm = "中性胺", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#Neutroamine.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Plasteel.label", TargetLanguage = "ChineseSimplified", SourceForm = "plasteel", TargetForm = "玻璃钢", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Plasteel.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Synthread.label", TargetLanguage = "ChineseSimplified", SourceForm = "synthread", TargetForm = "合成纤维", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Synthread.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:DevilstrandCloth.label", TargetLanguage = "ChineseSimplified", SourceForm = "devilstrand", TargetForm = "魔菇布", PartOfSpeech = "名词 / noun", ContextHint = "织物/制作材料：由恶魔菇纤维制成的布，不指作物本体。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#DevilstrandCloth.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Hyperweave.label", TargetLanguage = "ChineseSimplified", SourceForm = "hyperweave", TargetForm = "超织物", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Hyperweave.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Plant_Devilstrand.label", TargetLanguage = "ChineseSimplified", SourceForm = "devilstrand", TargetForm = "恶魔菇", PartOfSpeech = "名词 / noun", ContextHint = "种植/作物：活的恶魔菇，不指制成的魔菇布。", SourceReference = "Core/Defs/ThingDefs_Plants/Plants_Cultivated_Farm.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Cultivated_Farm.xml#Plant_Devilstrand.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Chemfuel.label", TargetLanguage = "ChineseSimplified", SourceForm = "chemfuel", TargetForm = "化合燃料", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#Chemfuel.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:ComponentIndustrial.label", TargetLanguage = "ChineseSimplified", SourceForm = "component", TargetForm = "零部件", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#ComponentIndustrial.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:ComponentSpacer.label", TargetLanguage = "ChineseSimplified", SourceForm = "advanced component", TargetForm = "高级零部件", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#ComponentSpacer.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Penoxycyline.label", TargetLanguage = "ChineseSimplified", SourceForm = "penoxycyline", TargetForm = "佩诺西林", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Penoxycyline.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Penoxycyline.xml#Penoxycyline.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Ambrosia.label", TargetLanguage = "ChineseSimplified", SourceForm = "ambrosia", TargetForm = "仙馐果", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Ambrosia.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Ambrosia.xml#Ambrosia.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:SmokeleafJoint.label", TargetLanguage = "ChineseSimplified", SourceForm = "smokeleaf joint", TargetForm = "大麻烟", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Smokeleaf.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Smokeleaf.xml#SmokeleafJoint.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:PsychiteTea.label", TargetLanguage = "ChineseSimplified", SourceForm = "psychite tea", TargetForm = "精神茶", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Psychite_Tea.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Psychite_Tea.xml#PsychiteTea.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Yayo.label", TargetLanguage = "ChineseSimplified", SourceForm = "yayo", TargetForm = "呀呦粉", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Psychite_Yayo.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Psychite_Yayo.xml#Yayo.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Flake.label", TargetLanguage = "ChineseSimplified", SourceForm = "flake", TargetForm = "薄片", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/Psychite_Flake.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Psychite_Flake.xml#Flake.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:WakeUp.label", TargetLanguage = "ChineseSimplified", SourceForm = "wake-up", TargetForm = "清醒丸", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏药物/消耗品名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/Drugs/WakeUp.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/WakeUp.xml#WakeUp.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:MedicineHerbal.label", TargetLanguage = "ChineseSimplified", SourceForm = "herbal medicine", TargetForm = "草药", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#MedicineHerbal.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:MedicineIndustrial.label", TargetLanguage = "ChineseSimplified", SourceForm = "medicine", TargetForm = "医药", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#MedicineIndustrial.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:MedicineUltratech.label", TargetLanguage = "ChineseSimplified", SourceForm = "glitterworld medicine", TargetForm = "闪耀世界医药", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#MedicineUltratech.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Uranium.label", TargetLanguage = "ChineseSimplified", SourceForm = "uranium", TargetForm = "铀", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Uranium.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Jade.label", TargetLanguage = "ChineseSimplified", SourceForm = "jade", TargetForm = "翡翠", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Jade.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Steel.label", TargetLanguage = "ChineseSimplified", SourceForm = "steel", TargetForm = "钢铁", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Steel.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Gold.label", TargetLanguage = "ChineseSimplified", SourceForm = "gold", TargetForm = "黄金", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Gold.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:Silver.label", TargetLanguage = "ChineseSimplified", SourceForm = "silver", TargetForm = "白银", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Silver.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:AIPersonaCore.label", TargetLanguage = "ChineseSimplified", SourceForm = "persona core", TargetForm = "人格核心", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Exotic.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Exotic.xml#AIPersonaCore.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:TechprofSubpersonaCore.label", TargetLanguage = "ChineseSimplified", SourceForm = "techprof subpersona core", TargetForm = "科技核心", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Exotic.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Exotic.xml#TechprofSubpersonaCore.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:PsychicAmplifier.label", TargetLanguage = "ChineseSimplified", SourceForm = "psylink neuroformer", TargetForm = "启灵装置", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/HediffDefs/Hediffs_Psycasts.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Hediffs_Psycasts.xml#PsychicAmplifier.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:PsychicAnimalPulser.label", TargetLanguage = "ChineseSimplified", SourceForm = "psychic animal pulser", TargetForm = "动物心灵脉冲发生器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Items/Items_Artifacts.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Artifacts.xml#PsychicAnimalPulser.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:OrbitalTargeterBombardment.label", TargetLanguage = "ChineseSimplified", SourceForm = "orbital bombardment targeter", TargetForm = "轨道轰炸靶向器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Misc/Weapons/RangedSpecial.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/RangedSpecial.xml#OrbitalTargeterBombardment.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Core:ThingDef:OrbitalTargeterPowerBeam.label", TargetLanguage = "ChineseSimplified", SourceForm = "orbital power beam targeter", TargetForm = "轨道能量束靶向器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Core 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Core/Defs/ThingDefs_Misc/Weapons/RangedSpecial.xml -> Core/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/RangedSpecial.xml#OrbitalTargeterPowerBeam.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Apparel_PsyfocusHelmet.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex helmet", TargetForm = "灵质头盔", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Apparel_Psychic.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Apparel_Psychic.xml#Apparel_PsyfocusHelmet.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Apparel_EltexSkullcap.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex skullcap", TargetForm = "灵质头套", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Apparel_Psychic.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Apparel_Psychic.xml#Apparel_EltexSkullcap.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Apparel_PsyfocusShirt.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex shirt", TargetForm = "灵质衬衫", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Apparel_Psychic.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Apparel_Psychic.xml#Apparel_PsyfocusShirt.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Apparel_PsyfocusVest.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex vest", TargetForm = "灵质马甲", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Apparel_Psychic.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Apparel_Psychic.xml#Apparel_PsyfocusVest.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Apparel_PsyfocusRobe.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex robe", TargetForm = "灵质长袍", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Apparel_Psychic.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Apparel_Psychic.xml#Apparel_PsyfocusRobe.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Plant_TreeAnima.label", TargetLanguage = "ChineseSimplified", SourceForm = "anima tree", TargetForm = "仙树", PartOfSpeech = "名词 / noun", ContextHint = "Royalty 的心灵连接树木。", SourceReference = "Royalty/Defs/ThingDefs_Plants/Plants_Wild.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Wild.xml#Plant_TreeAnima.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:Plant_GrassAnima.label", TargetLanguage = "ChineseSimplified", SourceForm = "anima grass", TargetForm = "灵草", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的种植/植物相关名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Plants/Plants_Wild.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Wild.xml#Plant_GrassAnima.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Royalty:ThingDef:MeleeWeapon_PsyfocusStaff.label", TargetLanguage = "ChineseSimplified", SourceForm = "eltex staff", TargetForm = "灵质权杖", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Royalty 的服装/武器装备名称，使用对应游戏实体的义项。", SourceReference = "Royalty/Defs/ThingDefs_Misc/Weapons/PsychicWeapons.xml -> Royalty/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/PsychicWeapons.xml#MeleeWeapon_PsyfocusStaff.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Ideology:ThingDef:Plant_TreeGauranlen.label", TargetLanguage = "ChineseSimplified", SourceForm = "Gauranlen tree", TargetForm = "母树", PartOfSpeech = "名词 / noun", ContextHint = "Ideology 的树精关联树木。", SourceReference = "Ideology/Defs/ThingDefs_Plants/Plants_Special.xml -> Ideology/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Special.xml#Plant_TreeGauranlen.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Ideology:ThingDef:Plant_MossGauranlen.label", TargetLanguage = "ChineseSimplified", SourceForm = "Gauranlen moss", TargetForm = "母树苔藓", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Ideology 的种植/植物相关名称，使用对应游戏实体的义项。", SourceReference = "Ideology/Defs/ThingDefs_Plants/Plants_Special.xml -> Ideology/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Special.xml#Plant_MossGauranlen.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Ideology:ThingDef:Plant_PodGauranlen.label", TargetLanguage = "ChineseSimplified", SourceForm = "Gauranlen pod", TargetForm = "母树荚囊", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Ideology 的种植/植物相关名称，使用对应游戏实体的义项。", SourceReference = "Ideology/Defs/ThingDefs_Plants/Plants_Special.xml -> Ideology/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Special.xml#Plant_PodGauranlen.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Ideology:ThingDef:GauranlenSeed.label", TargetLanguage = "ChineseSimplified", SourceForm = "Gauranlen seed", TargetForm = "母树种子", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Ideology 的种植/植物相关名称，使用对应游戏实体的义项。", SourceReference = "Ideology/Defs/ThingDefs_Plants/Plants_Special.xml -> Ideology/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Plants_Special.xml#GauranlenSeed.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Ideology:ThingDef:Dryad_Medicinemaker.label", TargetLanguage = "ChineseSimplified", SourceForm = "medicinemaker dryad", TargetForm = "药师树精", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Ideology 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Ideology/Defs/ThingDefs_Races/Races_Animal_Special.xml -> Ideology/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Races_Animal_Special.xml#Dryad_Medicinemaker.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:Mechlink.label", TargetLanguage = "ChineseSimplified", SourceForm = "mechlink", TargetForm = "机控中枢", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/HediffDefs/Hediffs_Mechanitor.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Hediffs_Mechanitor.xml#Mechlink.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:HemogenPack.label", TargetLanguage = "ChineseSimplified", SourceForm = "hemogen pack", TargetForm = "血原包", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/ThingDefs_Items/Items_Food.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Food.xml#HemogenPack.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:Wastepack.label", TargetLanguage = "ChineseSimplified", SourceForm = "toxic wastepack", TargetForm = "有毒垃圾", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的工业制品/制造原料名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#Wastepack.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:WastepackAtomizer.label", TargetLanguage = "ChineseSimplified", SourceForm = "wastepack atomizer", TargetForm = "垃圾分解器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/ThingDefs_Buildings/Buildings_Misc.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Misc.xml#WastepackAtomizer.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:ArchiteCapsule.label", TargetLanguage = "ChineseSimplified", SourceForm = "archite capsule", TargetForm = "超凡胶囊", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/ThingDefs_Items/Items_Various.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Various.xml#ArchiteCapsule.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:SignalChip.label", TargetLanguage = "ChineseSimplified", SourceForm = "signal chip", TargetForm = "同步信号芯片", PartOfSpeech = "名词 / noun", ContextHint = "Biotech 的同步信号芯片物品。", SourceReference = "Biotech/Defs/ThingDefs_Items/Items_Resource_Manufactured.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Manufactured.xml#SignalChip.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Biotech:ThingDef:Mech_Diabolus.label", TargetLanguage = "ChineseSimplified", SourceForm = "diabolus", TargetForm = "炼狱魔王", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Biotech 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Biotech/Defs/ThingDefs_Races/Races_Mechanoids_SuperHeavy.xml -> Biotech/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Races_Mechanoids_SuperHeavy.xml#Mech_Diabolus.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:Bioferrite.label", TargetLanguage = "ChineseSimplified", SourceForm = "bioferrite", TargetForm = "活铁", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的制作材料/原料名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Items/Items_Resource_Stuff.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Stuff.xml#Bioferrite.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:Shard.label", TargetLanguage = "ChineseSimplified", SourceForm = "shard", TargetForm = "暗黑超凡碎片", PartOfSpeech = "名词 / noun", ContextHint = "Anomaly 的暗黑超凡碎片物品；普通碎片不是这个义项。", SourceReference = "Anomaly/Defs/ThingDefs_Items/Items_Various.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Various.xml#Shard.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:BioferriteHarvester.label", TargetLanguage = "ChineseSimplified", SourceForm = "bioferrite harvester", TargetForm = "活铁采集器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Buildings/Buildings_Production.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Production.xml#BioferriteHarvester.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:BioferriteShaper.label", TargetLanguage = "ChineseSimplified", SourceForm = "bioferrite shaper", TargetForm = "活铁塑造台", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Buildings/Buildings_Production.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Production.xml#BioferriteShaper.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:BioferriteGenerator.label", TargetLanguage = "ChineseSimplified", SourceForm = "bioferrite generator", TargetForm = "活铁发电机", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Buildings/Buildings_Power.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Power.xml#BioferriteGenerator.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:ShardInhibitor.label", TargetLanguage = "ChineseSimplified", SourceForm = "shard inhibitor", TargetForm = "碎片阻滞器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Buildings/Buildings_Misc.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Misc.xml#ShardInhibitor.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Anomaly:ThingDef:ShardBeacon.label", TargetLanguage = "ChineseSimplified", SourceForm = "shard beacon", TargetForm = "碎片信标", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Anomaly 的游戏物品/装备/植物名称，使用对应游戏实体的义项。", SourceReference = "Anomaly/Defs/ThingDefs_Buildings/Buildings_PsychicRituals.xml -> Anomaly/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_PsychicRituals.xml#ShardBeacon.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:Gravcore.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravcore", TargetForm = "逆重核心", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Items/Items_Resource_Misc.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Misc.xml#Gravcore.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:GravlitePanel.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravlite panel", TargetForm = "逆重板", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Items/Items_Resource_Misc.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Items_Resource_Misc.xml#GravlitePanel.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:GravshipHull.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravship hull", TargetForm = "逆重飞船舱壁", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Buildings/Buildings_Gravship.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Gravship.xml#GravshipHull.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:GravcorePowerCell.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravcore power cell", TargetForm = "逆重核心能量电池", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Buildings/Buildings_Gravship.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Gravship.xml#GravcorePowerCell.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:GravshipShieldGenerator.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravship shield generator", TargetForm = "逆重飞船护盾发生器", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Buildings/Buildings_Gravship.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Buildings_Gravship.xml#GravshipShieldGenerator.label", IsBuiltIn = true };
            yield return new ReferenceDictionaryEntry { EntryId = "builtin:zh-cn:Odyssey:ThingDef:GravshipLandingMarker.label", TargetLanguage = "ChineseSimplified", SourceForm = "gravship landing zone", TargetForm = "逆重飞船着陆区", PartOfSpeech = "名词 / noun", ContextHint = "RimWorld Odyssey 的逆重飞船相关物品/建筑名称，使用对应游戏实体的义项。", SourceReference = "Odyssey/Defs/ThingDefs_Misc/Ethereal_Various.xml -> Odyssey/Languages/ChineseSimplified (简体中文).tar:DefInjected/ThingDef/Ethereal_Various.xml#GravshipLandingMarker.label", IsBuiltIn = true };
        }
    }
}
