using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;
using Verse;
using RimWorld;
// 這個檔案負責導出用模板內容。
// EN: This file generates export template text.

namespace AutoTranslator_Core
{
    // 這個類別負責 導出範本 的主要流程與狀態。
    // EN: This class manages the main workflow and state for ExportTemplates.
    internal static class ExportTemplates
    {
        // 這個方法負責取得 XmlWatermark 資料。
        // EN: This method gets XML watermark.
        public static string GetXmlWatermark(ExportableModInfo mod)
        {
            return $@"<!--
  ============================================================
  WARNING: AUTO-GENERATED MACHINE TRANSLATION - DO NOT REDISTRIBUTE
  ============================================================

  This file was generated by Auto Translation Core for personal use only.

  - Original mod copyright belongs to the original author.
  - This translation is an unauthorized derivative work.
  - Public redistribution (Steam Workshop, NEXUS, etc.) is PROHIBITED.
  - Use this as a draft for manual translation work only.

  Generation Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
  Source Mod: {mod.ModName} ({mod.PackageId})
  Generator: Auto Translation Core

  If you found this file uploaded somewhere, please report to:
  - Steam Workshop: Report > DMCA
  - The original mod author
  ============================================================
-->
";
        }

        // 這個方法負責取得 AboutXml 資料。
        // EN: This method gets about XML.
        public static string GetAboutXml(ExportableModInfo mod)
        {
            return $@"<?xml version=""1.0"" encoding=""utf-8""?>
<!--
  WARNING: MACHINE TRANSLATION - DO NOT REDISTRIBUTE
  This is an unauthorized derivative work.
  Original copyright belongs to the author of {mod.ModName}.
-->
<ModMetaData>
    <name>[MachineTrans-Draft] {mod.ModName}</name>
    <author>WARNING: Machine Translated, Not For Public Distribution</author>
    <packageId>localdraft.machinetrans.{mod.PackageId.ToLower()}</packageId>
    <description>WARNING: This is an AI machine translation draft. Strictly for personal or human-polishing use.

Forbidden:
- Uploading to Steam Workshop
- Public redistribution
- Impersonating official translation

Allowed:
- Personal local use
- As a starting point for human translation

Original Mod: {mod.ModName}
Original PackageId: {mod.PackageId}

Generated by: Auto Translation Core
Generation Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
    </description>
    <supportedVersions>
        <li>1.6</li>
    </supportedVersions>
    <modDependencies>
        <li>
            <packageId>{mod.PackageId}</packageId>
            <displayName>{mod.ModName}</displayName>
        </li>
    </modDependencies>
    <loadAfter>
        <li>{mod.PackageId}</li>
    </loadAfter>
</ModMetaData>";
        }

        // 這個方法負責取得 Readme 資料。
        // EN: This method gets readme.
        public static string GetReadme(List<ExportableModInfo> mods)
        {

            var sb = new StringBuilder();
            foreach (var m in mods)
            {
                sb.AppendLine($"  - {m.ModName} ({m.PackageId})");
                sb.AppendLine($"      DefInjected: {m.DefInjectedCount}, Keyed: {m.KeyedCount}");
            }


            return "ATC_Export_Readme_Full".Translate(
                DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                mods.Count,
                sb.ToString()
            ).ToString();
        }

        // 這個方法負責取得 ConsentRecord 資料。
        // EN: This method gets consent record.
        public static string GetConsentRecord(string timestamp, string version, int count)
        {

            return "ATC_Export_ConsentRecord_Full".Translate(
                timestamp,
                version,
                count,
                Environment.MachineName,
                Environment.OSVersion.ToString(),
                DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")
            ).ToString();
        }
    }
}
